# https://hub.docker.com/_/postgres

version: "3"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: togodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
